### ISSUE TITLE
Kirby v4 compatibility

### ISSUE THREAD

**Issue by radibit** [johannschopplich/kirby-headless#1]
Hey @johannschopplich 👋

Thank you for the great plugin that enhances the KQL and the experience of using Kirby as a headless CMS!

I wanted to check if there is a planned support of the plugin for the next major version of Kirby https://getkirby.com/releases/4.0?

**Comment by johannschopplich** [comment]
Hi there, @radibit!

Absolutely, it will come. I'm looking forward to Kirby v4, especially for the built-in blocks field preview. 

I'm waiting for the beta releases. Then, I will work on the migration. Note: I don't think there's much to do, because most features the plugin uses will not change by Kirby 4. The migration path will be a minimum, I guess.

**Comment by radibit** [comment]
Thank you for the speedy answer and confirmation of my initial impression after checking on a high-level perspective the code of the plugin!

Looking forward to Kirby v4, too :) Feel free to close this issue.

**Comment by johannschopplich** [comment]
Let's keep it open as a reminder. 😉

**Comment by johannschopplich** [comment]
Depends on https://github.com/getkirby/kql/issues/49
